version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [zip]
    name_template: '{{ .ProjectName }}-{{ .GitVersion }}-{{ .Os }}-{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
