version: 2

release:
    github:
      owner: xymaxim
      name: ypb
    draft: true
    prerelease: auto
    
before:
  hooks:
    - go mod tidy

builds:
  - binary: ypb
    main: ./cmd/ypb/
    env:
      - CGO_ENABLED=0
    ldflags: "-s -w -X github.com/xymaxim/ypb/internal/version.GitVersion={{ .Tag }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [zip]
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
