FROM golang:1.25-alpine AS builder
RUN apk update && apk add --no-cache make git curl unzip
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="${PATH}:/root/.bun/bin"
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN make build

FROM scratch
LABEL org.opencontainers.image.title="Ypb"
LABEL org.opencontainers.image.description="Ypb binary image."
LABEL org.opencontainers.image.source="https://github.com/xymaxim/ypb"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"

COPY --from=builder /build/ypb /ypb
